# Generated by Django 4.1.3 on 2022-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_modeldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
